package com.netty;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorsData.proto

public final class SensorsDataPOJO {
  private SensorsDataPOJO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 PEF = 500;</code>
     */
    int getPEF();

    /**
     * <code>int32 FEV1 = 2600;</code>
     */
    int getFEV1();

    /**
     * <code>int32 FVC = 3000;</code>
     */
    int getFVC();

    /**
     * <code>int32 SAO2 = 98;</code>
     */
    int getSAO2();

    /**
     * <code>int32 PR = 75;</code>
     */
    int getPR();

    /**
     * <code>int32 VT = 550;</code>
     */
    int getVT();

    /**
     * <code>int32 PM = 30;</code>
     */
    int getPM();

    /**
     * <code>int32 RH = 20;</code>
     */
    int getRH();
  }
  /**
   * <pre>
   *protobuf 使用message管理数据
   *会在StudentPOJO外部生成一个内部类Student，他是真正发送的Proto对象
   * </pre>
   *
   * Protobuf type {@code Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      pEF_ = 0;
      fEV1_ = 0;
      fVC_ = 0;
      sAO2_ = 0;
      pR_ = 0;
      vT_ = 0;
      pM_ = 0;
      rH_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 160: {

              rH_ = input.readInt32();
              break;
            }
            case 240: {

              pM_ = input.readInt32();
              break;
            }
            case 600: {

              pR_ = input.readInt32();
              break;
            }
            case 784: {

              sAO2_ = input.readInt32();
              break;
            }
            case 4000: {

              pEF_ = input.readInt32();
              break;
            }
            case 4400: {

              vT_ = input.readInt32();
              break;
            }
            case 20800: {

              fEV1_ = input.readInt32();
              break;
            }
            case 24000: {

              fVC_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SensorsDataPOJO.internal_static_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SensorsDataPOJO.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SensorsDataPOJO.Data.class, SensorsDataPOJO.Data.Builder.class);
    }

    public static final int PEF_FIELD_NUMBER = 500;
    private int pEF_;
    /**
     * <code>int32 PEF = 500;</code>
     */
    public int getPEF() {
      return pEF_;
    }

    public static final int FEV1_FIELD_NUMBER = 2600;
    private int fEV1_;
    /**
     * <code>int32 FEV1 = 2600;</code>
     */
    public int getFEV1() {
      return fEV1_;
    }

    public static final int FVC_FIELD_NUMBER = 3000;
    private int fVC_;
    /**
     * <code>int32 FVC = 3000;</code>
     */
    public int getFVC() {
      return fVC_;
    }

    public static final int SAO2_FIELD_NUMBER = 98;
    private int sAO2_;
    /**
     * <code>int32 SAO2 = 98;</code>
     */
    public int getSAO2() {
      return sAO2_;
    }

    public static final int PR_FIELD_NUMBER = 75;
    private int pR_;
    /**
     * <code>int32 PR = 75;</code>
     */
    public int getPR() {
      return pR_;
    }

    public static final int VT_FIELD_NUMBER = 550;
    private int vT_;
    /**
     * <code>int32 VT = 550;</code>
     */
    public int getVT() {
      return vT_;
    }

    public static final int PM_FIELD_NUMBER = 30;
    private int pM_;
    /**
     * <code>int32 PM = 30;</code>
     */
    public int getPM() {
      return pM_;
    }

    public static final int RH_FIELD_NUMBER = 20;
    private int rH_;
    /**
     * <code>int32 RH = 20;</code>
     */
    public int getRH() {
      return rH_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rH_ != 0) {
        output.writeInt32(20, rH_);
      }
      if (pM_ != 0) {
        output.writeInt32(30, pM_);
      }
      if (pR_ != 0) {
        output.writeInt32(75, pR_);
      }
      if (sAO2_ != 0) {
        output.writeInt32(98, sAO2_);
      }
      if (pEF_ != 0) {
        output.writeInt32(500, pEF_);
      }
      if (vT_ != 0) {
        output.writeInt32(550, vT_);
      }
      if (fEV1_ != 0) {
        output.writeInt32(2600, fEV1_);
      }
      if (fVC_ != 0) {
        output.writeInt32(3000, fVC_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, rH_);
      }
      if (pM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(30, pM_);
      }
      if (pR_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(75, pR_);
      }
      if (sAO2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(98, sAO2_);
      }
      if (pEF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(500, pEF_);
      }
      if (vT_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(550, vT_);
      }
      if (fEV1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2600, fEV1_);
      }
      if (fVC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3000, fVC_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SensorsDataPOJO.Data)) {
        return super.equals(obj);
      }
      SensorsDataPOJO.Data other = (SensorsDataPOJO.Data) obj;

      boolean result = true;
      result = result && (getPEF()
          == other.getPEF());
      result = result && (getFEV1()
          == other.getFEV1());
      result = result && (getFVC()
          == other.getFVC());
      result = result && (getSAO2()
          == other.getSAO2());
      result = result && (getPR()
          == other.getPR());
      result = result && (getVT()
          == other.getVT());
      result = result && (getPM()
          == other.getPM());
      result = result && (getRH()
          == other.getRH());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEF_FIELD_NUMBER;
      hash = (53 * hash) + getPEF();
      hash = (37 * hash) + FEV1_FIELD_NUMBER;
      hash = (53 * hash) + getFEV1();
      hash = (37 * hash) + FVC_FIELD_NUMBER;
      hash = (53 * hash) + getFVC();
      hash = (37 * hash) + SAO2_FIELD_NUMBER;
      hash = (53 * hash) + getSAO2();
      hash = (37 * hash) + PR_FIELD_NUMBER;
      hash = (53 * hash) + getPR();
      hash = (37 * hash) + VT_FIELD_NUMBER;
      hash = (53 * hash) + getVT();
      hash = (37 * hash) + PM_FIELD_NUMBER;
      hash = (53 * hash) + getPM();
      hash = (37 * hash) + RH_FIELD_NUMBER;
      hash = (53 * hash) + getRH();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SensorsDataPOJO.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorsDataPOJO.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorsDataPOJO.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorsDataPOJO.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorsDataPOJO.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorsDataPOJO.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorsDataPOJO.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorsDataPOJO.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorsDataPOJO.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SensorsDataPOJO.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorsDataPOJO.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorsDataPOJO.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SensorsDataPOJO.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobuf 使用message管理数据
     *会在StudentPOJO外部生成一个内部类Student，他是真正发送的Proto对象
     * </pre>
     *
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        SensorsDataPOJO.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SensorsDataPOJO.internal_static_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SensorsDataPOJO.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SensorsDataPOJO.Data.class, SensorsDataPOJO.Data.Builder.class);
      }

      // Construct using SensorsDataPOJO.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pEF_ = 0;

        fEV1_ = 0;

        fVC_ = 0;

        sAO2_ = 0;

        pR_ = 0;

        vT_ = 0;

        pM_ = 0;

        rH_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SensorsDataPOJO.internal_static_Data_descriptor;
      }

      @java.lang.Override
      public SensorsDataPOJO.Data getDefaultInstanceForType() {
        return SensorsDataPOJO.Data.getDefaultInstance();
      }

      @java.lang.Override
      public SensorsDataPOJO.Data build() {
        SensorsDataPOJO.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SensorsDataPOJO.Data buildPartial() {
        SensorsDataPOJO.Data result = new SensorsDataPOJO.Data(this);
        result.pEF_ = pEF_;
        result.fEV1_ = fEV1_;
        result.fVC_ = fVC_;
        result.sAO2_ = sAO2_;
        result.pR_ = pR_;
        result.vT_ = vT_;
        result.pM_ = pM_;
        result.rH_ = rH_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SensorsDataPOJO.Data) {
          return mergeFrom((SensorsDataPOJO.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SensorsDataPOJO.Data other) {
        if (other == SensorsDataPOJO.Data.getDefaultInstance()) return this;
        if (other.getPEF() != 0) {
          setPEF(other.getPEF());
        }
        if (other.getFEV1() != 0) {
          setFEV1(other.getFEV1());
        }
        if (other.getFVC() != 0) {
          setFVC(other.getFVC());
        }
        if (other.getSAO2() != 0) {
          setSAO2(other.getSAO2());
        }
        if (other.getPR() != 0) {
          setPR(other.getPR());
        }
        if (other.getVT() != 0) {
          setVT(other.getVT());
        }
        if (other.getPM() != 0) {
          setPM(other.getPM());
        }
        if (other.getRH() != 0) {
          setRH(other.getRH());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SensorsDataPOJO.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SensorsDataPOJO.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pEF_ ;
      /**
       * <code>int32 PEF = 500;</code>
       */
      public int getPEF() {
        return pEF_;
      }
      /**
       * <code>int32 PEF = 500;</code>
       */
      public Builder setPEF(int value) {
        
        pEF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PEF = 500;</code>
       */
      public Builder clearPEF() {
        
        pEF_ = 0;
        onChanged();
        return this;
      }

      private int fEV1_ ;
      /**
       * <code>int32 FEV1 = 2600;</code>
       */
      public int getFEV1() {
        return fEV1_;
      }
      /**
       * <code>int32 FEV1 = 2600;</code>
       */
      public Builder setFEV1(int value) {
        
        fEV1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 FEV1 = 2600;</code>
       */
      public Builder clearFEV1() {
        
        fEV1_ = 0;
        onChanged();
        return this;
      }

      private int fVC_ ;
      /**
       * <code>int32 FVC = 3000;</code>
       */
      public int getFVC() {
        return fVC_;
      }
      /**
       * <code>int32 FVC = 3000;</code>
       */
      public Builder setFVC(int value) {
        
        fVC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 FVC = 3000;</code>
       */
      public Builder clearFVC() {
        
        fVC_ = 0;
        onChanged();
        return this;
      }

      private int sAO2_ ;
      /**
       * <code>int32 SAO2 = 98;</code>
       */
      public int getSAO2() {
        return sAO2_;
      }
      /**
       * <code>int32 SAO2 = 98;</code>
       */
      public Builder setSAO2(int value) {
        
        sAO2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SAO2 = 98;</code>
       */
      public Builder clearSAO2() {
        
        sAO2_ = 0;
        onChanged();
        return this;
      }

      private int pR_ ;
      /**
       * <code>int32 PR = 75;</code>
       */
      public int getPR() {
        return pR_;
      }
      /**
       * <code>int32 PR = 75;</code>
       */
      public Builder setPR(int value) {
        
        pR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PR = 75;</code>
       */
      public Builder clearPR() {
        
        pR_ = 0;
        onChanged();
        return this;
      }

      private int vT_ ;
      /**
       * <code>int32 VT = 550;</code>
       */
      public int getVT() {
        return vT_;
      }
      /**
       * <code>int32 VT = 550;</code>
       */
      public Builder setVT(int value) {
        
        vT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 VT = 550;</code>
       */
      public Builder clearVT() {
        
        vT_ = 0;
        onChanged();
        return this;
      }

      private int pM_ ;
      /**
       * <code>int32 PM = 30;</code>
       */
      public int getPM() {
        return pM_;
      }
      /**
       * <code>int32 PM = 30;</code>
       */
      public Builder setPM(int value) {
        
        pM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PM = 30;</code>
       */
      public Builder clearPM() {
        
        pM_ = 0;
        onChanged();
        return this;
      }

      private int rH_ ;
      /**
       * <code>int32 RH = 20;</code>
       */
      public int getRH() {
        return rH_;
      }
      /**
       * <code>int32 RH = 20;</code>
       */
      public Builder setRH(int value) {
        
        rH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 RH = 20;</code>
       */
      public Builder clearRH() {
        
        rH_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final SensorsDataPOJO.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SensorsDataPOJO.Data();
    }

    public static SensorsDataPOJO.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SensorsDataPOJO.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SensorsData.proto\"p\n\004Data\022\014\n\003PEF\030\364\003 \001(" +
      "\005\022\r\n\004FEV1\030\250\024 \001(\005\022\014\n\003FVC\030\270\027 \001(\005\022\014\n\004SAO2\030b" +
      " \001(\005\022\n\n\002PR\030K \001(\005\022\013\n\002VT\030\246\004 \001(\005\022\n\n\002PM\030\036 \001(" +
      "\005\022\n\n\002RH\030\024 \001(\005B\021B\017SensorsDataPOJOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "PEF", "FEV1", "FVC", "SAO2", "PR", "VT", "PM", "RH", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
